### ISSUE TITLE
realgud debugger

### ISSUE THREAD

**Issue by dhiraj113** [emacs-tw/awesome-emacs#151]
Just came across the realgud emacs package https://melpa.org/#/realgud. Its a emacs front-end for debuggers. Looks like a good candidate to be added to the awesome emacs list.

**Comment by kuanyui** [comment]
PR please

**Comment by LinFelix** [comment]
How about a list of debuggers as well? Or should that be an issue on its own?

**Comment by kuanyui** [comment]
Feel free to create a new category as long as you think it's needed :)

**Comment by agsdot** [comment]
Just added realgud in [PR# 193](https://github.com/emacs-tw/awesome-emacs/pull/193).

Put it in the general programming category @kuanyui . @LinFelix , not sure about creating a list/category because there is only that one debugger yet so far. 

Closing issue for now. If you want to adjust/move the placement of the realgud link, a future PR can be put in.
