### ISSUE TITLE
Stackoverflow / howdoi

### ISSUE THREAD

**Issue by nofxx** [emacs-tw/awesome-emacs#96]
This one is very cool, dunno where to put it tho:

https://github.com/arthurnn/howdoi-emacs

**Comment by atykhonov** [comment]
JFYI: it depends on external python script `howdoi`. You could try https://github.com/atykhonov/emacs-howdoi which works without that dependency.

**Comment by nofxx** [comment]
@atykhonov that's very cool.
I'm using yours google-translate too. Ty.

**Comment by atykhonov** [comment]
Nice to know! :-) Thank you! But as for me, it is hard to say that these are mine, really. The real owner is community. Even `emacs-howdoi`, which was written from the scratch by me. Because the initial idea was dropped by Tom in the Emacs mailing list. When first version was released, he tested it a lot, sent feedbacks, propositions etc. Without Tom's help I didn't even start it :-) As for `google-translate` there is a long story in the end of which I'm just (currently) temporal maintainer of it :-) It is grown due to the combined efforts of community!

**Comment by agsdot** [comment]
emacs-howdoi added in [PR 210](https://github.com/emacs-tw/awesome-emacs/pull/210).

Closing issue.
